/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth-service';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from 'ionic-angular/components/grid/grid';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from '@angular/forms/src/directives/ng_form';
import * as import29 from '@angular/forms/src/directives/control_container';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.LoadingController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import13.ComponentFactory<import0.LoginPage> = new import13.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Content_2_4:import14.Wrapper_Content;
  _text_3:any;
  _el_4:any;
  _Row_4_3:import15.Wrapper_Row;
  _text_5:any;
  _el_6:any;
  _Col_6_3:import15.Wrapper_Col;
  _text_7:any;
  _el_8:any;
  _Col_8_3:import15.Wrapper_Col;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _Col_13_3:import15.Wrapper_Col;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _NgForm_18_3:import16.Wrapper_NgForm;
  _ControlContainer_18_4:any;
  _NgControlStatusGroup_18_5:import17.Wrapper_NgControlStatusGroup;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _Row_21_3:import15.Wrapper_Row;
  _text_22:any;
  _el_23:any;
  _Col_23_3:import15.Wrapper_Col;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Button_25_4:import18.Wrapper_Button;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','login-content');
    this.renderer.setElementAttribute(this._el_2,'padding','');
    this._appEl_2 = new import3.AppElement(2,(null as any),this,this._el_2);
    var compView_2:any = import14.viewFactory_Content0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Content_2_4 = new import14.Wrapper_Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_2.initComponent(this._Content_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','logo-row');
    this._Row_4_3 = new import15.Wrapper_Row();
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-col',(null as any));
    this._Col_6_3 = new import15.Wrapper_Col();
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_8,'id','logo');
    this.renderer.setElementAttribute(this._el_8,'width-67','');
    this._Col_8_3 = new import15.Wrapper_Col();
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'src','img/logo-app.png');
    this._text_11 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_4,'ion-col',(null as any));
    this._Col_13_3 = new import15.Wrapper_Col();
    this._text_14 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','login-box');
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'form',(null as any));
    this._NgForm_18_3 = new import16.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_18_4 = this._NgForm_18_3.context;
    this._NgControlStatusGroup_18_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_18_4);
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_18,'\n\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_18,'ion-row',(null as any));
    this._Row_21_3 = new import15.Wrapper_Row();
    this._text_22 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','signup-col');
    this._Col_23_3 = new import15.Wrapper_Col();
    this._text_24 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','submit-btn');
    this.renderer.setElementAttribute(this._el_25,'full','');
    this.renderer.setElementAttribute(this._el_25,'ion-button','');
    this.renderer.setElementAttribute(this._el_25,'type','submit');
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import18.viewFactory_Button0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Button_25_4 = new import18.Wrapper_Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_25),this.renderer);
    this._appEl_25.initComponent(this._Button_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'Login with Facebook',(null as any));
    compView_25.create(this._Button_25_4.context,[([] as any[]).concat([this._text_26])],(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._text_28 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_18,'\n\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n',(null as any));
    compView_2.create(this._Content_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_15,
        this._el_16,
        this._text_32
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_18,'ngSubmit',this.eventHandler(this._handle_ngSubmit_18_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_18,'submit',this.eventHandler(this._handle_submit_18_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_18,'reset',this.eventHandler(this._handle_reset_18_2.bind(this)));
    const subscription_0:any = this._NgForm_18_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_18_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.Col) && (6 === requestNodeIndex))) { return this._Col_6_3.context; }
    if (((token === import26.Col) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Col_8_3.context; }
    if (((token === import26.Col) && (13 === requestNodeIndex))) { return this._Col_13_3.context; }
    if (((token === import26.Row) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Row_4_3.context; }
    if (((token === import27.Button) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Button_25_4.context; }
    if (((token === import26.Col) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Col_23_3.context; }
    if (((token === import26.Row) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Row_21_3.context; }
    if (((token === import28.NgForm) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgForm_18_3.context; }
    if (((token === import29.ControlContainer) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ControlContainer_18_4; }
    if (((token === import30.NgControlStatusGroup) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControlStatusGroup_18_5.context; }
    if (((token === import31.Content) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Content_2_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._Row_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Col_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._Col_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    this._Col_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._NgForm_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._NgControlStatusGroup_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    this._Row_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Col_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_10:any = '';
    this._Button_25_4.check_full(currVal_10,throwOnChange,false);
    if (this._Button_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_25_4.context.ngAfterContentInit(); } }
    const currVal_0:any = this._Content_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._NgControlStatusGroup_18_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_18_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_18_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_18_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_18_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_18_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_2_4.context.ngOnDestroy();
  }
  private _handle_ngSubmit_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_18_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_18_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_18_3.context.onReset()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}