/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './report-two';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../providers/crime-service';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-params';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import31 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import32 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import35 from 'ionic-angular/config/config';
import * as import36 from '@angular/core/src/linker/element_ref';
import * as import37 from 'ionic-angular/navigation/view-controller';
import * as import38 from 'ionic-angular/components/app/app';
import * as import39 from 'ionic-angular/components/toolbar/toolbar';
import * as import40 from 'ionic-angular/util/keyboard';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from 'ionic-angular/components/tabs/tabs';
import * as import43 from '@angular/core/src/linker/template_ref';
import * as import44 from 'ionic-angular/gestures/gesture-controller';
import * as import45 from 'ionic-angular/util/form';
import * as import46 from 'ionic-angular/components/item/item-reorder';
import * as import47 from 'ionic-angular/components/picker/picker';
import * as import48 from 'ionic-angular/platform/platform';
import * as import49 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import50 from 'ionic-angular/components/icon/icon';
import * as import51 from 'ionic-angular/components/button/button';
import * as import52 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import53 from 'ionic-angular/components/navbar/navbar';
import * as import54 from '@angular/common/src/directives/ng_if';
import * as import55 from 'ionic-angular/components/label/label';
import * as import56 from 'ionic-angular/components/datetime/datetime';
import * as import57 from '@angular/forms/src/directives/control_value_accessor';
import * as import58 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import59 from '@angular/forms/src/directives/ng_control';
import * as import60 from '@angular/forms/src/directives/ng_control_status';
import * as import61 from 'ionic-angular/components/item/item';
import * as import62 from 'ionic-angular/components/input/input';
import * as import63 from 'ionic-angular/components/option/option';
import * as import64 from 'ionic-angular/components/select/select';
import * as import65 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import66 from '@angular/forms/src/directives/control_container';
import * as import67 from 'ionic-angular/components/list/list';
import * as import68 from 'ionic-angular/components/content/content';
export class Wrapper_ReportTwoPage {
  context:import0.ReportTwoPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this.changed = false;
    this.context = new import0.ReportTwoPage(p0,p1,p2,p3,p4,p5);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ReportTwoPage_Host:import2.RenderComponentType = (null as any);
class _View_ReportTwoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ReportTwoPage_0_4:Wrapper_ReportTwoPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ReportTwoPage_Host0,renderType_ReportTwoPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-report-two',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ReportTwoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ReportTwoPage_0_4 = new Wrapper_ReportTwoPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.CrimeService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController),this.parentInjector.get(import13.NavParams));
    this._appEl_0.initComponent(this._ReportTwoPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ReportTwoPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ReportTwoPage) && (0 === requestNodeIndex))) { return this._ReportTwoPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ReportTwoPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportTwoPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ReportTwoPage_Host === (null as any))) { (renderType_ReportTwoPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ReportTwoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ReportTwoPageNgFactory:import15.ComponentFactory<import0.ReportTwoPage> = new import15.ComponentFactory<import0.ReportTwoPage>('page-report-two',viewFactory_ReportTwoPage_Host0,import0.ReportTwoPage);
const styles_ReportTwoPage:any[] = ([] as any[]);
var renderType_ReportTwoPage:import2.RenderComponentType = (null as any);
class _View_ReportTwoPage0 extends import1.AppView<import0.ReportTwoPage> {
  _viewQuery_reportSlider_0:import16.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _Header_1_3:import17.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import18.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import19.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _ToolbarItem_8_3:import20.Wrapper_ToolbarItem;
  _query_Button_8_0:import16.QueryList<any>;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Button_10_4:import21.Wrapper_Button;
  _el_11:any;
  _Icon_11_3:import22.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import23.Wrapper_Content;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import24.Wrapper_NgIf;
  _text_20:any;
  _el_21:any;
  _List_21_3:import25.Wrapper_List;
  _text_22:any;
  _el_23:any;
  _FormGroupDirective_23_3:import26.Wrapper_FormGroupDirective;
  _ControlContainer_23_4:any;
  _NgControlStatusGroup_23_5:import27.Wrapper_NgControlStatusGroup;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Item_25_4:import28.Wrapper_Item;
  _ItemContent_25_5:import28.Wrapper_ItemContent;
  _query_Label_25_0:import16.QueryList<any>;
  _query_Button_25_1:import16.QueryList<any>;
  _query_Icon_25_2:import16.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import29.Wrapper_Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _DateTime_30_4:import30.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_30_5:any[];
  _FormControlName_30_6:import31.Wrapper_FormControlName;
  _NgControl_30_7:any;
  _NgControlStatus_30_8:import27.Wrapper_NgControlStatus;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _Item_33_4:import28.Wrapper_Item;
  _ItemContent_33_5:import28.Wrapper_ItemContent;
  _query_Label_33_0:import16.QueryList<any>;
  _query_Button_33_1:import16.QueryList<any>;
  _query_Icon_33_2:import16.QueryList<any>;
  _text_34:any;
  _el_35:any;
  _Label_35_3:import29.Wrapper_Label;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _DateTime_38_4:import30.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_38_5:any[];
  _FormControlName_38_6:import31.Wrapper_FormControlName;
  _NgControl_38_7:any;
  _NgControlStatus_38_8:import27.Wrapper_NgControlStatus;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Item_41_4:import28.Wrapper_Item;
  _ItemContent_41_5:import28.Wrapper_ItemContent;
  _query_Label_41_0:import16.QueryList<any>;
  _query_Button_41_1:import16.QueryList<any>;
  _query_Icon_41_2:import16.QueryList<any>;
  _text_42:any;
  _el_43:any;
  _Label_43_3:import29.Wrapper_Label;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _FormControlName_46_4:import31.Wrapper_FormControlName;
  _NgControl_46_5:any;
  _NgControlStatus_46_6:import27.Wrapper_NgControlStatus;
  _TextInput_46_7:import32.Wrapper_TextInput;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _Item_49_4:import28.Wrapper_Item;
  _ItemContent_49_5:import28.Wrapper_ItemContent;
  _query_Label_49_0:import16.QueryList<any>;
  _query_Button_49_1:import16.QueryList<any>;
  _query_Icon_49_2:import16.QueryList<any>;
  _text_50:any;
  _el_51:any;
  _Label_51_3:import29.Wrapper_Label;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _Select_54_4:import33.Wrapper_Select;
  _NG_VALUE_ACCESSOR_54_5:any[];
  _FormControlName_54_6:import31.Wrapper_FormControlName;
  _NgControl_54_7:any;
  _NgControlStatus_54_8:import27.Wrapper_NgControlStatus;
  _query_Option_54_0:import16.QueryList<any>;
  _text_55:any;
  _el_56:any;
  _Option_56_3:import34.Wrapper_Option;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _Option_59_3:import34.Wrapper_Option;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _Option_62_3:import34.Wrapper_Option;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import3.AppElement;
  _Item_67_4:import28.Wrapper_Item;
  _ItemContent_67_5:import28.Wrapper_ItemContent;
  _query_Label_67_0:import16.QueryList<any>;
  _query_Button_67_1:import16.QueryList<any>;
  _query_Icon_67_2:import16.QueryList<any>;
  _text_68:any;
  _el_69:any;
  _Label_69_3:import29.Wrapper_Label;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  /*private*/ _appEl_72:import3.AppElement;
  _FormControlName_72_4:import31.Wrapper_FormControlName;
  _NgControl_72_5:any;
  _NgControlStatus_72_6:import27.Wrapper_NgControlStatus;
  _TextArea_72_7:import32.Wrapper_TextArea;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  /*private*/ _appEl_78:import3.AppElement;
  _Button_78_4:import21.Wrapper_Button;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ReportTwoPage0,renderType_ReportTwoPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_reportSlider_0 = new import16.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import17.Wrapper_Header(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import37.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import38.App),this.parentInjector.get(import37.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import39.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Report 2/2',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_8,'end','');
    this._ToolbarItem_8_3 = new import20.Wrapper_ToolbarItem(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import39.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_8_0 = new import16.QueryList<any>();
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'icon-left','');
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this._appEl_10 = new import3.AppElement(10,8,this,this._el_10);
    var compView_10:any = import21.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import21.Wrapper_Button((null as any),'',this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4.context,([] as any[]),compView_10);
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','arrow-back');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import22.Wrapper_Icon(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),' Prev',(null as any));
      compView_10.create(this._Button_10_4.context,[([] as any[]).concat([
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_8]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_17,'padding','');
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import23.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import23.Wrapper_Content(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import38.App),this.parentInjector.get(import40.Keyboard),this.parentInjector.get(import41.NgZone),this.parentInjector.get(import37.ViewController,(null as any)),this.parentInjector.get(import42.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_19 = new import3.AppElement(19,17,this,this._anchor_19);
    this._TemplateRef_19_5 = new import43.TemplateRef_(this._appEl_19,viewFactory_ReportTwoPage1);
    this._NgIf_19_6 = new import24.Wrapper_NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText((null as any),'\n ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_21_3 = new import25.Wrapper_List(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import44.GestureController));
    this._text_22 = this.renderer.createText(this._el_21,'\n     ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'form',(null as any));
    this._FormGroupDirective_23_3 = new import26.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_23_4 = this._FormGroupDirective_23_3.context;
    this._NgControlStatusGroup_23_5 = new import27.Wrapper_NgControlStatusGroup(this._ControlContainer_23_4);
    this._text_24 = this.renderer.createText(this._el_23,'\n\n       ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import28.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import28.Wrapper_Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import46.ItemReorder,(null as any)));
    this._ItemContent_25_5 = new import28.Wrapper_ItemContent();
    this._query_Label_25_0 = new import16.QueryList<any>();
    this._query_Button_25_1 = new import16.QueryList<any>();
    this._query_Icon_25_2 = new import16.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_27_3 = new import29.Wrapper_Label(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_27),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Date*',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_30,'displayFormat','DD/MM/YYYY');
    this.renderer.setElementAttribute(this._el_30,'formControlName','reportDate');
    this._appEl_30 = new import3.AppElement(30,25,this,this._el_30);
    var compView_30:any = import30.viewFactory_DateTime0(this.viewUtils,this.injector(30),this._appEl_30);
    this._DateTime_30_4 = new import30.Wrapper_DateTime(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_30),this.renderer,this._Item_25_4.context,this.parentInjector.get(import47.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_30_5 = [this._DateTime_30_4.context];
    this._FormControlName_30_6 = new import31.Wrapper_FormControlName(this._ControlContainer_23_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_30_5);
    this._NgControl_30_7 = this._FormControlName_30_6.context;
    this._NgControlStatus_30_8 = new import27.Wrapper_NgControlStatus(this._NgControl_30_7);
    this._appEl_30.initComponent(this._DateTime_30_4.context,([] as any[]),compView_30);
    compView_30.create(this._DateTime_30_4.context,([] as any[]),(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3.context]);
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_27]),
      ([] as any[]).concat([
        this._text_26,
        this._text_29,
        this._text_31
      ]
      ),
      ([] as any[]).concat([this._el_30]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_23,'\n\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','item item-block');
    this._appEl_33 = new import3.AppElement(33,23,this,this._el_33);
    var compView_33:any = import28.viewFactory_Item0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Item_33_4 = new import28.Wrapper_Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_33),this.renderer,this.parentInjector.get(import46.ItemReorder,(null as any)));
    this._ItemContent_33_5 = new import28.Wrapper_ItemContent();
    this._query_Label_33_0 = new import16.QueryList<any>();
    this._query_Button_33_1 = new import16.QueryList<any>();
    this._query_Icon_33_2 = new import16.QueryList<any>();
    this._appEl_33.initComponent(this._Item_33_4.context,([] as any[]),compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_35_3 = new import29.Wrapper_Label(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_35),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Time*',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_38,'displayFormat','H:mm');
    this.renderer.setElementAttribute(this._el_38,'formControlName','reportTime');
    this._appEl_38 = new import3.AppElement(38,33,this,this._el_38);
    var compView_38:any = import30.viewFactory_DateTime0(this.viewUtils,this.injector(38),this._appEl_38);
    this._DateTime_38_4 = new import30.Wrapper_DateTime(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_38),this.renderer,this._Item_33_4.context,this.parentInjector.get(import47.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_38_5 = [this._DateTime_38_4.context];
    this._FormControlName_38_6 = new import31.Wrapper_FormControlName(this._ControlContainer_23_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_38_5);
    this._NgControl_38_7 = this._FormControlName_38_6.context;
    this._NgControlStatus_38_8 = new import27.Wrapper_NgControlStatus(this._NgControl_38_7);
    this._appEl_38.initComponent(this._DateTime_38_4.context,([] as any[]),compView_38);
    compView_38.create(this._DateTime_38_4.context,([] as any[]),(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_33_0.reset([this._Label_35_3.context]);
    this._Item_33_4.context.contentLabel = this._query_Label_33_0.first;
    compView_33.create(this._Item_33_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_35]),
      ([] as any[]).concat([
        this._text_34,
        this._text_37,
        this._text_39
      ]
      ),
      ([] as any[]).concat([this._el_38]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_23,'\n\n\n         ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import3.AppElement(41,23,this,this._el_41);
    var compView_41:any = import28.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import28.Wrapper_Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_41),this.renderer,this.parentInjector.get(import46.ItemReorder,(null as any)));
    this._ItemContent_41_5 = new import28.Wrapper_ItemContent();
    this._query_Label_41_0 = new import16.QueryList<any>();
    this._query_Button_41_1 = new import16.QueryList<any>();
    this._query_Icon_41_2 = new import16.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_43_3 = new import29.Wrapper_Label(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_43),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Damages Value R$',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_46,'formControlName','damage');
    this.renderer.setElementAttribute(this._el_46,'placeholder','100.00');
    this.renderer.setElementAttribute(this._el_46,'type','number');
    this._appEl_46 = new import3.AppElement(46,41,this,this._el_46);
    var compView_46:any = import32.viewFactory_TextInput0(this.viewUtils,this.injector(46),this._appEl_46);
    this._FormControlName_46_4 = new import31.Wrapper_FormControlName(this._ControlContainer_23_4,(null as any),(null as any),(null as any));
    this._NgControl_46_5 = this._FormControlName_46_4.context;
    this._NgControlStatus_46_6 = new import27.Wrapper_NgControlStatus(this._NgControl_46_5);
    this._TextInput_46_7 = new import32.Wrapper_TextInput(this.parentInjector.get(import35.Config),this.parentInjector.get(import45.Form),this._Item_41_4.context,this.parentInjector.get(import38.App),this.parentInjector.get(import48.Platform),new import36.ElementRef(this._el_46),this.renderer,this._Content_17_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_46_5);
    this._appEl_46.initComponent(this._TextInput_46_7.context,([] as any[]),compView_46);
    compView_46.create(this._TextInput_46_7.context,([] as any[]),(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._query_Label_41_0.reset([this._Label_43_3.context]);
    this._Item_41_4.context.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_43]),
      ([] as any[]).concat([
        this._text_42,
        this._text_45,
        this._text_47
      ]
      ),
      ([] as any[]).concat([this._el_46]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText(this._el_23,'\n\n         ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','item item-block');
    this._appEl_49 = new import3.AppElement(49,23,this,this._el_49);
    var compView_49:any = import28.viewFactory_Item0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Item_49_4 = new import28.Wrapper_Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_49),this.renderer,this.parentInjector.get(import46.ItemReorder,(null as any)));
    this._ItemContent_49_5 = new import28.Wrapper_ItemContent();
    this._query_Label_49_0 = new import16.QueryList<any>();
    this._query_Button_49_1 = new import16.QueryList<any>();
    this._query_Icon_49_2 = new import16.QueryList<any>();
    this._appEl_49.initComponent(this._Item_49_4.context,([] as any[]),compView_49);
    this._text_50 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_51_3 = new import29.Wrapper_Label(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_51),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Type*',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_54,'formControlName','type');
    this._appEl_54 = new import3.AppElement(54,49,this,this._el_54);
    var compView_54:any = import33.viewFactory_Select0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Select_54_4 = new import33.Wrapper_Select(this.parentInjector.get(import38.App),this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_54),this.renderer,this._Item_49_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_54_5 = [this._Select_54_4.context];
    this._FormControlName_54_6 = new import31.Wrapper_FormControlName(this._ControlContainer_23_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_54_5);
    this._NgControl_54_7 = this._FormControlName_54_6.context;
    this._NgControlStatus_54_8 = new import27.Wrapper_NgControlStatus(this._NgControl_54_7);
    this._query_Option_54_0 = new import16.QueryList<any>();
    this._appEl_54.initComponent(this._Select_54_4.context,([] as any[]),compView_54);
    this._text_55 = this.renderer.createText((null as any),'\n                 ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_56,'checked','true');
    this.renderer.setElementAttribute(this._el_56,'value','public');
    this._Option_56_3 = new import34.Wrapper_Option(new import36.ElementRef(this._el_56));
    this._text_57 = this.renderer.createText(this._el_56,'Public',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n                 ',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_59,'value','friends');
    this._Option_59_3 = new import34.Wrapper_Option(new import36.ElementRef(this._el_59));
    this._text_60 = this.renderer.createText(this._el_59,'Friends Only',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n                 ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this.renderer.setElementAttribute(this._el_62,'value','private');
    this._Option_62_3 = new import34.Wrapper_Option(new import36.ElementRef(this._el_62));
    this._text_63 = this.renderer.createText(this._el_62,'Private',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n             ',(null as any));
    compView_54.create(this._Select_54_4.context,([] as any[]),(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._query_Label_49_0.reset([this._Label_51_3.context]);
    this._Item_49_4.context.contentLabel = this._query_Label_49_0.first;
    compView_49.create(this._Item_49_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_51]),
      ([] as any[]).concat([
        this._text_50,
        this._text_53,
        this._text_65
      ]
      ),
      ([] as any[]).concat([this._el_54]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_66 = this.renderer.createText(this._el_23,'\n\n         ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','item item-block');
    this._appEl_67 = new import3.AppElement(67,23,this,this._el_67);
    var compView_67:any = import28.viewFactory_Item0(this.viewUtils,this.injector(67),this._appEl_67);
    this._Item_67_4 = new import28.Wrapper_Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_67),this.renderer,this.parentInjector.get(import46.ItemReorder,(null as any)));
    this._ItemContent_67_5 = new import28.Wrapper_ItemContent();
    this._query_Label_67_0 = new import16.QueryList<any>();
    this._query_Button_67_1 = new import16.QueryList<any>();
    this._query_Icon_67_2 = new import16.QueryList<any>();
    this._appEl_67.initComponent(this._Item_67_4.context,([] as any[]),compView_67);
    this._text_68 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_69 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_69,'stacked','');
    this._Label_69_3 = new import29.Wrapper_Label(this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_69),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Description',(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n             ',(null as any));
    this._el_72 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_72,'formControlName','description');
    this.renderer.setElementAttribute(this._el_72,'placeholder','Descreva como ocorreu o crime.');
    this._appEl_72 = new import3.AppElement(72,67,this,this._el_72);
    var compView_72:any = import32.viewFactory_TextArea0(this.viewUtils,this.injector(72),this._appEl_72);
    this._FormControlName_72_4 = new import31.Wrapper_FormControlName(this._ControlContainer_23_4,(null as any),(null as any),(null as any));
    this._NgControl_72_5 = this._FormControlName_72_4.context;
    this._NgControlStatus_72_6 = new import27.Wrapper_NgControlStatus(this._NgControl_72_5);
    this._TextArea_72_7 = new import32.Wrapper_TextArea(this.parentInjector.get(import35.Config),this.parentInjector.get(import45.Form),this._Item_67_4.context,this.parentInjector.get(import38.App),this.parentInjector.get(import48.Platform),new import36.ElementRef(this._el_72),this.renderer,this._Content_17_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_72_5);
    this._appEl_72.initComponent(this._TextArea_72_7.context,([] as any[]),compView_72);
    compView_72.create(this._TextArea_72_7.context,([] as any[]),(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._query_Label_67_0.reset([this._Label_69_3.context]);
    this._Item_67_4.context.contentLabel = this._query_Label_67_0.first;
    compView_67.create(this._Item_67_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_69]),
      ([] as any[]).concat([
        this._text_68,
        this._text_71,
        this._text_73
      ]
      ),
      ([] as any[]).concat([this._el_72]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_74 = this.renderer.createText(this._el_23,'\n\n         ',(null as any));
    this._text_75 = this.renderer.createText(this._el_23,'\n\n     ',(null as any));
    this._text_76 = this.renderer.createText(this._el_21,'\n\n ',(null as any));
    this._text_77 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_78 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_78,'color','danger');
    this.renderer.setElementAttribute(this._el_78,'ion-button','');
    this._appEl_78 = new import3.AppElement(78,17,this,this._el_78);
    var compView_78:any = import21.viewFactory_Button0(this.viewUtils,this.injector(78),this._appEl_78);
    this._Button_78_4 = new import21.Wrapper_Button((null as any),'',this.parentInjector.get(import35.Config),new import36.ElementRef(this._el_78),this.renderer);
    this._appEl_78.initComponent(this._Button_78_4.context,([] as any[]),compView_78);
    this._text_79 = this.renderer.createText((null as any),'Submit Report',(null as any));
    compView_78.create(this._Button_78_4.context,[([] as any[]).concat([this._text_79])],(null as any));
    this._text_80 = this.renderer.createText((null as any),'\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._appEl_19,
        this._text_20,
        this._el_21,
        this._text_77,
        this._el_78,
        this._text_80
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_81 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_23,'submit',this.eventHandler(this._handle_submit_23_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'reset',this.eventHandler(this._handle_reset_23_1.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_30,'keyup.space',this.eventHandler(this._handle_keyup_space_30_1.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_38,'click',this.eventHandler(this._handle_click_38_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_38,'keyup.space',this.eventHandler(this._handle_keyup_space_38_1.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_54,'click',this.eventHandler(this._handle_click_54_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_54,'keyup.space',this.eventHandler(this._handle_keyup_space_54_1.bind(this)));
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_78,'click',this.eventHandler(this._handle_click_78_0.bind(this)));
    this._viewQuery_reportSlider_0.reset(([] as any[]));
    this.context.reportFormList = this._viewQuery_reportSlider_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import50.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import51.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Button_10_4.context; }
    if (((token === import52.ToolbarItem) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarItem_8_3.context; }
    if (((token === import53.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_3_4.context; }
    if (((token === import39.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_1_3.context; }
    if (((token === import43.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import54.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6.context; }
    if (((token === import55.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3.context; }
    if (((token === import56.DateTime) && (30 === requestNodeIndex))) { return this._DateTime_30_4.context; }
    if (((token === import57.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_5; }
    if (((token === import58.FormControlName) && (30 === requestNodeIndex))) { return this._FormControlName_30_6.context; }
    if (((token === import59.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_7; }
    if (((token === import60.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_8.context; }
    if (((token === import61.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_25_4.context; }
    if (((token === import61.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_25_5.context; }
    if (((token === import55.Label) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Label_35_3.context; }
    if (((token === import56.DateTime) && (38 === requestNodeIndex))) { return this._DateTime_38_4.context; }
    if (((token === import57.NG_VALUE_ACCESSOR) && (38 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_38_5; }
    if (((token === import58.FormControlName) && (38 === requestNodeIndex))) { return this._FormControlName_38_6.context; }
    if (((token === import59.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_7; }
    if (((token === import60.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_8.context; }
    if (((token === import61.Item) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_33_4.context; }
    if (((token === import61.ItemContent) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_33_5.context; }
    if (((token === import55.Label) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Label_43_3.context; }
    if (((token === import58.FormControlName) && (46 === requestNodeIndex))) { return this._FormControlName_46_4.context; }
    if (((token === import59.NgControl) && (46 === requestNodeIndex))) { return this._NgControl_46_5; }
    if (((token === import60.NgControlStatus) && (46 === requestNodeIndex))) { return this._NgControlStatus_46_6.context; }
    if (((token === import62.TextInput) && (46 === requestNodeIndex))) { return this._TextInput_46_7.context; }
    if (((token === import61.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Item_41_4.context; }
    if (((token === import61.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._ItemContent_41_5.context; }
    if (((token === import55.Label) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Label_51_3.context; }
    if (((token === import63.Option) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Option_56_3.context; }
    if (((token === import63.Option) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Option_59_3.context; }
    if (((token === import63.Option) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Option_62_3.context; }
    if (((token === import64.Select) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Select_54_4.context; }
    if (((token === import57.NG_VALUE_ACCESSOR) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NG_VALUE_ACCESSOR_54_5; }
    if (((token === import58.FormControlName) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._FormControlName_54_6.context; }
    if (((token === import59.NgControl) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgControl_54_7; }
    if (((token === import60.NgControlStatus) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgControlStatus_54_8.context; }
    if (((token === import61.Item) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Item_49_4.context; }
    if (((token === import61.ItemContent) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ItemContent_49_5.context; }
    if (((token === import55.Label) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Label_69_3.context; }
    if (((token === import58.FormControlName) && (72 === requestNodeIndex))) { return this._FormControlName_72_4.context; }
    if (((token === import59.NgControl) && (72 === requestNodeIndex))) { return this._NgControl_72_5; }
    if (((token === import60.NgControlStatus) && (72 === requestNodeIndex))) { return this._NgControlStatus_72_6.context; }
    if (((token === import62.TextArea) && (72 === requestNodeIndex))) { return this._TextArea_72_7.context; }
    if (((token === import61.Item) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Item_67_4.context; }
    if (((token === import61.ItemContent) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._ItemContent_67_5.context; }
    if (((token === import65.FormGroupDirective) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._FormGroupDirective_23_3.context; }
    if (((token === import66.ControlContainer) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ControlContainer_23_4; }
    if (((token === import60.NgControlStatusGroup) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgControlStatusGroup_23_5.context; }
    if (((token === import67.List) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._List_21_3.context; }
    if (((token === import51.Button) && ((78 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Button_78_4.context; }
    if (((token === import68.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    this._ToolbarItem_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    if (this._Button_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'arrow-back';
    this._Icon_11_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_6:any = this.context.submitAttempt;
    this._NgIf_19_6.check_ngIf(currVal_6,throwOnChange,false);
    this._NgIf_19_6.detectChangesInternal(this,this._anchor_19,throwOnChange);
    this._List_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_9:any = this.context.reportForm;
    this._FormGroupDirective_23_3.check_form(currVal_9,throwOnChange,false);
    this._FormGroupDirective_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._NgControlStatusGroup_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ItemContent_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    this._Label_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_18:any = 'DD/MM/YYYY';
    this._DateTime_30_4.check_displayFormat(currVal_18,throwOnChange,false);
    this._DateTime_30_4.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_20:any = 'reportDate';
    this._FormControlName_30_6.check_name(currVal_20,throwOnChange,false);
    this._FormControlName_30_6.detectChangesInternal(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_8.detectChangesInternal(this,this._el_30,throwOnChange);
    if (this._Item_33_4.detectChangesInternal(this,this._el_33,throwOnChange)) { this._appEl_33.componentView.markAsCheckOnce(); }
    this._ItemContent_33_5.detectChangesInternal(this,this._el_33,throwOnChange);
    this._Label_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_29:any = 'H:mm';
    this._DateTime_38_4.check_displayFormat(currVal_29,throwOnChange,false);
    this._DateTime_38_4.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_31:any = 'reportTime';
    this._FormControlName_38_6.check_name(currVal_31,throwOnChange,false);
    this._FormControlName_38_6.detectChangesInternal(this,this._el_38,throwOnChange);
    this._NgControlStatus_38_8.detectChangesInternal(this,this._el_38,throwOnChange);
    if (this._Item_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    this._ItemContent_41_5.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Label_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_38:any = 'damage';
    this._FormControlName_46_4.check_name(currVal_38,throwOnChange,false);
    this._FormControlName_46_4.detectChangesInternal(this,this._el_46,throwOnChange);
    this._NgControlStatus_46_6.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_45:any = '100.00';
    this._TextInput_46_7.check_placeholder(currVal_45,throwOnChange,false);
    const currVal_46:any = 'number';
    this._TextInput_46_7.check_type(currVal_46,throwOnChange,false);
    this._TextInput_46_7.detectChangesInternal(this,this._el_46,throwOnChange);
    if (this._Item_49_4.detectChangesInternal(this,this._el_49,throwOnChange)) { this._appEl_49.componentView.markAsCheckOnce(); }
    this._ItemContent_49_5.detectChangesInternal(this,this._el_49,throwOnChange);
    this._Label_51_3.detectChangesInternal(this,this._el_51,throwOnChange);
    this._Select_54_4.detectChangesInternal(this,this._el_54,throwOnChange);
    const currVal_50:any = 'type';
    this._FormControlName_54_6.check_name(currVal_50,throwOnChange,false);
    this._FormControlName_54_6.detectChangesInternal(this,this._el_54,throwOnChange);
    this._NgControlStatus_54_8.detectChangesInternal(this,this._el_54,throwOnChange);
    const currVal_57:any = 'public';
    this._Option_56_3.check_value(currVal_57,throwOnChange,false);
    this._Option_56_3.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_58:any = 'friends';
    this._Option_59_3.check_value(currVal_58,throwOnChange,false);
    this._Option_59_3.detectChangesInternal(this,this._el_59,throwOnChange);
    const currVal_59:any = 'private';
    this._Option_62_3.check_value(currVal_59,throwOnChange,false);
    this._Option_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    if (this._Item_67_4.detectChangesInternal(this,this._el_67,throwOnChange)) { this._appEl_67.componentView.markAsCheckOnce(); }
    this._ItemContent_67_5.detectChangesInternal(this,this._el_67,throwOnChange);
    this._Label_69_3.detectChangesInternal(this,this._el_69,throwOnChange);
    const currVal_60:any = 'description';
    this._FormControlName_72_4.check_name(currVal_60,throwOnChange,false);
    this._FormControlName_72_4.detectChangesInternal(this,this._el_72,throwOnChange);
    this._NgControlStatus_72_6.detectChangesInternal(this,this._el_72,throwOnChange);
    const currVal_67:any = 'Descreva como ocorreu o crime.';
    this._TextArea_72_7.check_placeholder(currVal_67,throwOnChange,false);
    this._TextArea_72_7.detectChangesInternal(this,this._el_72,throwOnChange);
    const currVal_69:any = 'danger';
    this._Button_78_4.check_color(currVal_69,throwOnChange,false);
    if (this._Button_78_4.detectChangesInternal(this,this._el_78,throwOnChange)) { this._appEl_78.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_8_0.dirty) {
        this._query_Button_8_0.reset([this._Button_10_4.context]);
        this._ToolbarItem_8_3.context._buttons = this._query_Button_8_0;
        this._query_Button_8_0.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_33_1.dirty) {
        this._query_Button_33_1.reset(([] as any[]));
        this._Item_33_4.context._buttons = this._query_Button_33_1;
        this._query_Button_33_1.notifyOnChanges();
      }
      if (this._query_Icon_33_2.dirty) {
        this._query_Icon_33_2.reset(([] as any[]));
        this._Item_33_4.context._icons = this._query_Icon_33_2;
        this._query_Icon_33_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset(([] as any[]));
        this._Item_41_4.context._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset(([] as any[]));
        this._Item_41_4.context._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if (this._query_Option_54_0.dirty) {
        this._query_Option_54_0.reset([
          this._Option_56_3.context,
          this._Option_59_3.context,
          this._Option_62_3.context
        ]
        );
        this._Select_54_4.context.options = this._query_Option_54_0;
        this._query_Option_54_0.notifyOnChanges();
      }
      if (this._query_Button_49_1.dirty) {
        this._query_Button_49_1.reset(([] as any[]));
        this._Item_49_4.context._buttons = this._query_Button_49_1;
        this._query_Button_49_1.notifyOnChanges();
      }
      if (this._query_Icon_49_2.dirty) {
        this._query_Icon_49_2.reset(([] as any[]));
        this._Item_49_4.context._icons = this._query_Icon_49_2;
        this._query_Icon_49_2.notifyOnChanges();
      }
      if (this._query_Button_67_1.dirty) {
        this._query_Button_67_1.reset(([] as any[]));
        this._Item_67_4.context._buttons = this._query_Button_67_1;
        this._query_Button_67_1.notifyOnChanges();
      }
      if (this._query_Icon_67_2.dirty) {
        this._query_Icon_67_2.reset(([] as any[]));
        this._Item_67_4.context._icons = this._query_Icon_67_2;
        this._query_Icon_67_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_30_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_38_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_33_4.context.ngAfterContentInit(); }
      this._TextInput_46_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_41_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_54_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_49_4.context.ngAfterContentInit(); }
      this._TextArea_72_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_67_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_78_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Content_17_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_10:any = this._NgControlStatusGroup_23_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_23_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_23_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_23_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_23_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatusGroup_23_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_19:any = this._DateTime_30_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_30,'datetime-disabled',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = this._NgControlStatus_30_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_30_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_30_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_30_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_30_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_30_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_30:any = this._DateTime_38_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_38,'datetime-disabled',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_32:any = this._NgControlStatus_38_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_38,'ng-untouched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_38_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_38,'ng-touched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_38_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_38,'ng-pristine',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_38_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_38,'ng-dirty',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_38_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_38,'ng-valid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_38_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_38,'ng-invalid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_39:any = this._NgControlStatus_46_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_46,'ng-untouched',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_46_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_46,'ng-touched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_46_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_46,'ng-pristine',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_46_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_46,'ng-dirty',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_46_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_46,'ng-valid',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_46_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_46,'ng-invalid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_49:any = this._Select_54_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_54,'select-disabled',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_51:any = this._NgControlStatus_54_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_54,'ng-untouched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_54_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_54,'ng-touched',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_54_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_54,'ng-pristine',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_54_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_54,'ng-dirty',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_54_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_54,'ng-valid',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_54_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_54,'ng-invalid',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_61:any = this._NgControlStatus_72_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_72,'ng-untouched',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this._NgControlStatus_72_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_72,'ng-touched',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this._NgControlStatus_72_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_72,'ng-pristine',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_72_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_72,'ng-dirty',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_72_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_72,'ng-valid',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_72_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_72,'ng-invalid',currVal_66);
      this._expr_66 = currVal_66;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_11_3.context.ngOnDestroy();
    this._DateTime_30_4.context.ngOnDestroy();
    this._FormControlName_30_6.context.ngOnDestroy();
    this._DateTime_38_4.context.ngOnDestroy();
    this._FormControlName_38_6.context.ngOnDestroy();
    this._FormControlName_46_4.context.ngOnDestroy();
    this._TextInput_46_7.context.ngOnDestroy();
    this._Select_54_4.context.ngOnDestroy();
    this._FormControlName_54_6.context.ngOnDestroy();
    this._FormControlName_72_4.context.ngOnDestroy();
    this._TextArea_72_7.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.prev()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_23_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_23_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this._appEl_30.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_30_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_30_1($event:any):boolean {
    this._appEl_30.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_30_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_38_0($event:any):boolean {
    this._appEl_38.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_38_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_38_1($event:any):boolean {
    this._appEl_38.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_38_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_54_0($event:any):boolean {
    this._appEl_54.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_54_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_54_1($event:any):boolean {
    this._appEl_54.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_54_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_78_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.save()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ReportTwoPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ReportTwoPage> {
  if ((renderType_ReportTwoPage === (null as any))) { (renderType_ReportTwoPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_ReportTwoPage,{})); }
  return new _View_ReportTwoPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ReportTwoPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ReportTwoPage1,renderType_ReportTwoPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','color: #ea6153;');
    this._text_1 = this.renderer.createText(this._el_0,'Please fill out all details accurately.',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ReportTwoPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ReportTwoPage1(viewUtils,parentInjector,declarationEl);
}