/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './register';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth-service';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import18 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/components/item/item-reorder';
import * as import38 from 'ionic-angular/platform/platform';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from '@angular/forms/src/directives/validators';
import * as import42 from '@angular/forms/src/validators';
import * as import43 from '@angular/forms/src/directives/ng_model';
import * as import44 from '@angular/forms/src/directives/ng_control';
import * as import45 from '@angular/forms/src/directives/ng_control_status';
import * as import46 from 'ionic-angular/components/input/input';
import * as import47 from 'ionic-angular/components/item/item';
import * as import48 from 'ionic-angular/components/list/list';
import * as import49 from 'ionic-angular/components/grid/grid';
import * as import50 from 'ionic-angular/components/button/button';
import * as import51 from '@angular/forms/src/directives/ng_form';
import * as import52 from '@angular/forms/src/directives/control_container';
import * as import53 from 'ionic-angular/components/content/content';
export class Wrapper_RegisterPage {
  context:import0.RegisterPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.RegisterPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RegisterPage_Host:import2.RenderComponentType = (null as any);
class _View_RegisterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RegisterPage_0_4:Wrapper_RegisterPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage_Host0,renderType_RegisterPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-register',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegisterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RegisterPage_0_4 = new Wrapper_RegisterPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.AlertController));
    this._appEl_0.initComponent(this._RegisterPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RegisterPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RegisterPage) && (0 === requestNodeIndex))) { return this._RegisterPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RegisterPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RegisterPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RegisterPage_Host === (null as any))) { (renderType_RegisterPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RegisterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegisterPageNgFactory:import12.ComponentFactory<import0.RegisterPage> = new import12.ComponentFactory<import0.RegisterPage>('page-register',viewFactory_RegisterPage_Host0,import0.RegisterPage);
const styles_RegisterPage:any[] = ([] as any[]);
var renderType_RegisterPage:import2.RenderComponentType = (null as any);
class _View_RegisterPage0 extends import1.AppView<import0.RegisterPage> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import15.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import16.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _NgForm_13_3:import17.Wrapper_NgForm;
  _ControlContainer_13_4:any;
  _NgControlStatusGroup_13_5:import18.Wrapper_NgControlStatusGroup;
  _text_14:any;
  _el_15:any;
  _Row_15_3:import19.Wrapper_Row;
  _text_16:any;
  _el_17:any;
  _Col_17_3:import19.Wrapper_Col;
  _text_18:any;
  _el_19:any;
  _List_19_3:import20.Wrapper_List;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Item_21_4:import21.Wrapper_Item;
  _ItemContent_21_5:import21.Wrapper_ItemContent;
  _query_Label_21_0:import22.QueryList<any>;
  _query_Button_21_1:import22.QueryList<any>;
  _query_Icon_21_2:import22.QueryList<any>;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _RequiredValidator_23_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_5:any[];
  _NgModel_23_6:import24.Wrapper_NgModel;
  _NgControl_23_7:any;
  _NgControlStatus_23_8:import18.Wrapper_NgControlStatus;
  _TextInput_23_9:import25.Wrapper_TextInput;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Item_26_4:import21.Wrapper_Item;
  _ItemContent_26_5:import21.Wrapper_ItemContent;
  _query_Label_26_0:import22.QueryList<any>;
  _query_Button_26_1:import22.QueryList<any>;
  _query_Icon_26_2:import22.QueryList<any>;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _RequiredValidator_28_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_28_5:any[];
  _NgModel_28_6:import24.Wrapper_NgModel;
  _NgControl_28_7:any;
  _NgControlStatus_28_8:import18.Wrapper_NgControlStatus;
  _TextInput_28_9:import25.Wrapper_TextInput;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Row_34_3:import19.Wrapper_Row;
  _text_35:any;
  _el_36:any;
  _Col_36_3:import19.Wrapper_Col;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Button_38_4:import26.Wrapper_Button;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_39:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage0,renderType_RegisterPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','dark');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Register',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','login-content');
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import16.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import16.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','login-box');
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'form',(null as any));
    this._NgForm_13_3 = new import17.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_13_4 = this._NgForm_13_3.context;
    this._NgControlStatusGroup_13_5 = new import18.Wrapper_NgControlStatusGroup(this._ControlContainer_13_4);
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-row',(null as any));
    this._Row_15_3 = new import19.Wrapper_Row();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-col',(null as any));
    this._Col_17_3 = new import19.Wrapper_Col();
    this._text_18 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_19,'inset','');
    this._List_19_3 = new import20.Wrapper_List(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import35.GestureController));
    this._text_20 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','item item-block');
    this._appEl_21 = new import3.AppElement(21,19,this,this._el_21);
    var compView_21:any = import21.viewFactory_Item0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Item_21_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_21_5 = new import21.Wrapper_ItemContent();
    this._query_Label_21_0 = new import22.QueryList<any>();
    this._query_Button_21_1 = new import22.QueryList<any>();
    this._query_Icon_21_2 = new import22.QueryList<any>();
    this._appEl_21.initComponent(this._Item_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_23,'name','email');
    this.renderer.setElementAttribute(this._el_23,'placeholder','Email');
    this.renderer.setElementAttribute(this._el_23,'required','');
    this.renderer.setElementAttribute(this._el_23,'type','text');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(23),this._appEl_23);
    this._RequiredValidator_23_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_5 = [this._RequiredValidator_23_4.context];
    this._NgModel_23_6 = new import24.Wrapper_NgModel(this._ControlContainer_13_4,this._NG_VALIDATORS_23_5,(null as any),(null as any));
    this._NgControl_23_7 = this._NgModel_23_6.context;
    this._NgControlStatus_23_8 = new import18.Wrapper_NgControlStatus(this._NgControl_23_7);
    this._TextInput_23_9 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import36.Form),this._Item_21_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import38.Platform),new import28.ElementRef(this._el_23),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_23_7);
    this._appEl_23.initComponent(this._TextInput_23_9.context,([] as any[]),compView_23);
    compView_23.create(this._TextInput_23_9.context,([] as any[]),(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_21_0.reset(([] as any[]));
    this._Item_21_4.context.contentLabel = this._query_Label_21_0.first;
    compView_21.create(this._Item_21_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_22,
        this._text_24
      ]
      ),
      ([] as any[]).concat([this._el_23]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_19,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','item item-block');
    this._appEl_26 = new import3.AppElement(26,19,this,this._el_26);
    var compView_26:any = import21.viewFactory_Item0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Item_26_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_26_5 = new import21.Wrapper_ItemContent();
    this._query_Label_26_0 = new import22.QueryList<any>();
    this._query_Button_26_1 = new import22.QueryList<any>();
    this._query_Icon_26_2 = new import22.QueryList<any>();
    this._appEl_26.initComponent(this._Item_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','password');
    this.renderer.setElementAttribute(this._el_28,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_28,'required','');
    this.renderer.setElementAttribute(this._el_28,'type','password');
    this._appEl_28 = new import3.AppElement(28,26,this,this._el_28);
    var compView_28:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(28),this._appEl_28);
    this._RequiredValidator_28_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_28_5 = [this._RequiredValidator_28_4.context];
    this._NgModel_28_6 = new import24.Wrapper_NgModel(this._ControlContainer_13_4,this._NG_VALIDATORS_28_5,(null as any),(null as any));
    this._NgControl_28_7 = this._NgModel_28_6.context;
    this._NgControlStatus_28_8 = new import18.Wrapper_NgControlStatus(this._NgControl_28_7);
    this._TextInput_28_9 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import36.Form),this._Item_26_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import38.Platform),new import28.ElementRef(this._el_28),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_28_7);
    this._appEl_28.initComponent(this._TextInput_28_9.context,([] as any[]),compView_28);
    compView_28.create(this._TextInput_28_9.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_26_0.reset(([] as any[]));
    this._Item_26_4.context.contentLabel = this._query_Label_26_0.first;
    compView_26.create(this._Item_26_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_27,
        this._text_29
      ]
      ),
      ([] as any[]).concat([this._el_28]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_19,'\n\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_33 = this.renderer.createText(this._el_13,'\n\n      ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_13,'ion-row',(null as any));
    this._Row_34_3 = new import19.Wrapper_Row();
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','signup-col');
    this._Col_36_3 = new import19.Wrapper_Col();
    this._text_37 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','submit-btn');
    this.renderer.setElementAttribute(this._el_38,'full','');
    this.renderer.setElementAttribute(this._el_38,'ion-button','');
    this.renderer.setElementAttribute(this._el_38,'type','submit');
    this._appEl_38 = new import3.AppElement(38,36,this,this._el_38);
    var compView_38:any = import26.viewFactory_Button0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Button_38_4 = new import26.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Button_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'Register',(null as any));
    compView_38.create(this._Button_38_4.context,[([] as any[]).concat([this._text_39])],(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_13,'\n\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_44
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'ngSubmit',this.eventHandler(this._handle_ngSubmit_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'submit',this.eventHandler(this._handle_submit_13_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_13,'reset',this.eventHandler(this._handle_reset_13_2.bind(this)));
    const subscription_0:any = this._NgForm_13_3.context.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_13_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_23,'ngModelChange',this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_23_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_28,'ngModelChange',this.eventHandler(this._handle_ngModelChange_28_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_28_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_28_0.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import40.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import31.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import41.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_4.context; }
    if (((token === import42.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_5; }
    if (((token === import43.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_6.context; }
    if (((token === import44.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_7; }
    if (((token === import45.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_8.context; }
    if (((token === import46.TextInput) && (23 === requestNodeIndex))) { return this._TextInput_23_9.context; }
    if (((token === import47.Item) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Item_21_4.context; }
    if (((token === import47.ItemContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ItemContent_21_5.context; }
    if (((token === import41.RequiredValidator) && (28 === requestNodeIndex))) { return this._RequiredValidator_28_4.context; }
    if (((token === import42.NG_VALIDATORS) && (28 === requestNodeIndex))) { return this._NG_VALIDATORS_28_5; }
    if (((token === import43.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_6.context; }
    if (((token === import44.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_7; }
    if (((token === import45.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_8.context; }
    if (((token === import46.TextInput) && (28 === requestNodeIndex))) { return this._TextInput_28_9.context; }
    if (((token === import47.Item) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_26_4.context; }
    if (((token === import47.ItemContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_26_5.context; }
    if (((token === import48.List) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._List_19_3.context; }
    if (((token === import49.Col) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Col_17_3.context; }
    if (((token === import49.Row) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Row_15_3.context; }
    if (((token === import50.Button) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Button_38_4.context; }
    if (((token === import49.Col) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Col_36_3.context; }
    if (((token === import49.Row) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Row_34_3.context; }
    if (((token === import51.NgForm) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgForm_13_3.context; }
    if (((token === import52.ControlContainer) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ControlContainer_13_4; }
    if (((token === import45.NgControlStatusGroup) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgControlStatusGroup_13_5.context; }
    if (((token === import53.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'dark';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._NgForm_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._NgControlStatusGroup_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Row_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Col_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    this._List_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    this._ItemContent_21_5.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_14:any = '';
    this._RequiredValidator_23_4.check_required(currVal_14,throwOnChange,false);
    this._RequiredValidator_23_4.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_16:any = 'email';
    this._NgModel_23_6.check_name(currVal_16,throwOnChange,false);
    const currVal_17:any = this.context.registerCredentials.email;
    this._NgModel_23_6.check_model(currVal_17,throwOnChange,false);
    this._NgModel_23_6.detectChangesInternal(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_8.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_24:any = 'Email';
    this._TextInput_23_9.check_placeholder(currVal_24,throwOnChange,false);
    const currVal_25:any = 'text';
    this._TextInput_23_9.check_type(currVal_25,throwOnChange,false);
    this._TextInput_23_9.detectChangesInternal(this,this._el_23,throwOnChange);
    if (this._Item_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    this._ItemContent_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_27:any = '';
    this._RequiredValidator_28_4.check_required(currVal_27,throwOnChange,false);
    this._RequiredValidator_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_29:any = 'password';
    this._NgModel_28_6.check_name(currVal_29,throwOnChange,false);
    const currVal_30:any = this.context.registerCredentials.password;
    this._NgModel_28_6.check_model(currVal_30,throwOnChange,false);
    this._NgModel_28_6.detectChangesInternal(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_8.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_37:any = 'Password';
    this._TextInput_28_9.check_placeholder(currVal_37,throwOnChange,false);
    const currVal_38:any = 'password';
    this._TextInput_28_9.check_type(currVal_38,throwOnChange,false);
    this._TextInput_28_9.detectChangesInternal(this,this._el_28,throwOnChange);
    this._Row_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Col_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_40:any = '';
    this._Button_38_4.check_full(currVal_40,throwOnChange,false);
    if (this._Button_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_21_1.dirty) {
        this._query_Button_21_1.reset(([] as any[]));
        this._Item_21_4.context._buttons = this._query_Button_21_1;
        this._query_Button_21_1.notifyOnChanges();
      }
      if (this._query_Icon_21_2.dirty) {
        this._query_Icon_21_2.reset(([] as any[]));
        this._Item_21_4.context._icons = this._query_Icon_21_2;
        this._query_Icon_21_2.notifyOnChanges();
      }
      if (this._query_Button_26_1.dirty) {
        this._query_Button_26_1.reset(([] as any[]));
        this._Item_26_4.context._buttons = this._query_Button_26_1;
        this._query_Button_26_1.notifyOnChanges();
      }
      if (this._query_Icon_26_2.dirty) {
        this._query_Icon_26_2.reset(([] as any[]));
        this._Item_26_4.context._icons = this._query_Icon_26_2;
        this._query_Icon_26_2.notifyOnChanges();
      }
      this._TextInput_23_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_21_4.context.ngAfterContentInit(); }
      this._TextInput_28_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_26_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_38_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._NgControlStatusGroup_13_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_13_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_13_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_13_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_13_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_13_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_15:any = (this._RequiredValidator_23_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementAttribute(this._el_23,'required',((currVal_15 == (null as any))? (null as any): currVal_15.toString()));
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = this._NgControlStatus_23_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_23_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_23_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_23_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_23_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_23_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_28:any = (this._RequiredValidator_28_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementAttribute(this._el_28,'required',((currVal_28 == (null as any))? (null as any): currVal_28.toString()));
      this._expr_28 = currVal_28;
    }
    const currVal_31:any = this._NgControlStatus_28_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_28,'ng-untouched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_28_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_28,'ng-touched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_28_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_28,'ng-pristine',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_28_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_28,'ng-dirty',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_28_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_28,'ng-valid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_28_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_28,'ng-invalid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_39:boolean = !this._NgForm_13_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementProperty(this._el_38,'disabled',currVal_39);
      this._expr_39 = currVal_39;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_23_6.context.ngOnDestroy();
    this._TextInput_23_9.context.ngOnDestroy();
    this._NgModel_28_6.context.ngOnDestroy();
    this._TextInput_28_9.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngSubmit_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.register()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_13_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_13_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_13_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.registerCredentials.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.registerCredentials.password = $event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegisterPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RegisterPage> {
  if ((renderType_RegisterPage === (null as any))) { (renderType_RegisterPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_RegisterPage,{})); }
  return new _View_RegisterPage0(viewUtils,parentInjector,declarationEl);
}