/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './report';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../providers/crime-service';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/components/toast/toast';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/components/icon/icon';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/menu/menu-toggle';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from 'ionic-angular/components/content/content';
export class Wrapper_ReportPage {
  context:import0.ReportPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this.changed = false;
    this.context = new import0.ReportPage(p0,p1,p2,p3,p4,p5);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ReportPage_Host:import2.RenderComponentType = (null as any);
class _View_ReportPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ReportPage_0_4:Wrapper_ReportPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ReportPage_Host0,renderType_ReportPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-report',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ReportPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ReportPage_0_4 = new Wrapper_ReportPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.CrimeService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController),this.parentInjector.get(import13.ToastController));
    this._appEl_0.initComponent(this._ReportPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ReportPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ReportPage) && (0 === requestNodeIndex))) { return this._ReportPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ReportPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ReportPage_Host === (null as any))) { (renderType_ReportPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ReportPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ReportPageNgFactory:import15.ComponentFactory<import0.ReportPage> = new import15.ComponentFactory<import0.ReportPage>('page-report',viewFactory_ReportPage_Host0,import0.ReportPage);
const styles_ReportPage:any[] = ([] as any[]);
var renderType_ReportPage:import2.RenderComponentType = (null as any);
class _View_ReportPage0 extends import1.AppView<import0.ReportPage> {
  _viewQuery_map_0:import16.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _Header_1_3:import17.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import18.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import19.Wrapper_Button;
  _MenuToggle_5_5:import20.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import21.Wrapper_ToolbarItem;
  _query_Button_5_0:import16.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import22.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import23.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _ToolbarItem_14_3:import21.Wrapper_ToolbarItem;
  _query_Button_14_0:import16.QueryList<any>;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Button_16_4:import19.Wrapper_Button;
  _text_17:any;
  _el_18:any;
  _Icon_18_3:import22.Wrapper_Icon;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Content_24_4:import24.Wrapper_Content;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ReportPage0,renderType_ReportPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_map_0 = new import16.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import17.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import19.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import19.Wrapper_Button('','',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import20.Wrapper_MenuToggle(this.parentInjector.get(import29.MenuController),new import26.ElementRef(this._el_5),this.parentInjector.get(import27.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import16.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import22.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      \n      ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import23.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import23.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),' Report 1/2 ',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_14,'end','');
    this._ToolbarItem_14_3 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_14_0 = new import16.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'icon-right','');
    this.renderer.setElementAttribute(this._el_16,'ion-button','');
    this._appEl_16 = new import3.AppElement(16,14,this,this._el_16);
    var compView_16:any = import19.viewFactory_Button0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Button_16_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_16),this.renderer);
    this._appEl_16.initComponent(this._Button_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'Next ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_18,'name','arrow-forward');
    this.renderer.setElementAttribute(this._el_18,'role','img');
    this._Icon_18_3 = new import22.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_18),this.renderer);
      compView_16.create(this._Button_16_4.context,[([] as any[]).concat([
        this._text_17,
        this._el_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([this._el_14]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_13,
        this._text_20,
        this._text_21
      ]
      )
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_24 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_24 = new import3.AppElement(24,(null as any),this,this._el_24);
    var compView_24:any = import24.viewFactory_Content0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Content_24_4 = new import24.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_24),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_24.initComponent(this._Content_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'data-tap-disabled','true');
    this.renderer.setElementAttribute(this._el_26,'id','map');
    this._text_27 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_24.create(this._Content_24_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_25,
        this._el_26,
        this._text_27
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._viewQuery_map_0.reset([new import26.ElementRef(this._el_26)]);
    this.context.mapElement = this._viewQuery_map_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import35.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import36.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import37.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import38.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import34.Icon) && (18 === requestNodeIndex))) { return this._Icon_18_3.context; }
    if (((token === import35.Button) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_16_4.context; }
    if (((token === import37.ToolbarItem) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_14_3.context; }
    if (((token === import39.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Navbar_3_4.context; }
    if (((token === import30.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Header_1_3.context; }
    if (((token === import40.Content) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Content_24_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_7_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    if (this._Button_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'arrow-forward';
    this._Icon_18_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Content_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_14_0.dirty) {
        this._query_Button_14_0.reset([this._Button_16_4.context]);
        this._ToolbarItem_14_3.context._buttons = this._query_Button_14_0;
        this._query_Button_14_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_16_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_18_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_18,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_24_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_24,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_18_3.context.ngOnDestroy();
    this._Content_24_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.next()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ReportPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ReportPage> {
  if ((renderType_ReportPage === (null as any))) { (renderType_ReportPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_ReportPage,{})); }
  return new _View_ReportPage0(viewUtils,parentInjector,declarationEl);
}